### ISSUE TITLE
Why isn't the billboard in the main menu?

### ISSUE THREAD

**Issue by SolarSupremacy** [TommySoucy/H3MP#187]
Since H3MP works independently of the scene player(s) are loaded in, loading into T&H to connect to someone and then going back to the main menu is a bit inconvenient.

If it's to ensure people aren't just installing H3MP and then trying to play any game mode, might I suggest making it so when the ServerListController.state is anything other than Main or MainWaiting, the unsupported game modes in the main menu are obstructed/greyed out?

Unrelated:
I'm personally curious about the possibility of replacing the main menu scene entirely (not specifically for H3MP, but any custom modpacks centered around a specific gametype). If you have any insight on that, I'd love to know if you think it's reasonably possible or not.

**Comment by TommySoucy** [comment]
The H3MP TNH menu is in TNH lobby because its the TNH menu, not a general H3MP. Instances are not revant unless you are in TNH. 

ServerListController is unused.

Don't make an issue with siggestions about the functionnality of the mod unless you know how it functions.

The unrelated stuff doesn't belong on the issues of H3MP repo, as it is unrelated.
