### ISSUE TITLE
Shotgun shells go off in inventory

### ISSUE THREAD

**Issue by ATJonzie** [TommySoucy/H3MP#222]
There is a problem where shotgun shells or any other ammo that is not housed in a magazine go off when shot or explosions are nearby even when spawn locked.

**Comment by TommySoucy** [comment]
When does it happen? If you have a round in a slot and someone else hits it with a melee weapon, it goes off? If so that will be fixed when I get around to #167

**Comment by ATJonzie** [comment]
I'll hop on and do some testing with my brother real quick

**Comment by ATJonzie** [comment]
it is set off by explosions of all kind both friendly and enemies as well as lasers.

**Comment by TommySoucy** [comment]
Are they set off by your own explosions? Do the lasers have to hit the rounds directly?

**Comment by ATJonzie** [comment]
Own explosives yes, it seems the laser only really happens if it hits the front of you around the ammo slots.

**Comment by TommySoucy** [comment]
There was a problem with the round damage and splode patches I've fixed for next release that should fix this. If grenades from your own explosions cause rounds to go off, its a problem with yet another patch I need to test

**Comment by TommySoucy** [comment]
This isn't necessarily relevant to you, I just want to keep note.

The idea is that only the controller of the item that causes damage (or the best potential host), calls Damage() on the damageable.  A player should not be able to damage a round (possibly causing it to Splode()) in their quickbelt, not only because collisions on the slotted round are disabled, but also because round.Damage() checks whether it is in QBS before applying damage. 

Currently, when in a scene with other players, a player could damage the rounds in their own QB. There are 2 things that enabled this:

- In MP, currently, items in QB will still have collisions enabled for remote players. Planned to fix this in #167 . This means that if a player fires a projectile at a round on their QB, a remote player, firing the same projectile in the same direction and everything, will have their side's bullet hit the round. Which should have been fine, but leading to the second point:
- Rounds were not being added to TrackedItemByDamageable, we had forgotten to add them in there for some reason. This caused damageable patches, like the one for BallisticProjectile to think that the round was client sided, and could therefore safely apply damage to it.

This has been fixed by:

1. Making sure rounds are now added to TrackedItemByDamageable upon tracking
2. Making sure only the controller of the round processes damage so that only the controller can ever Splode() it
