### ISSUE TITLE
Custom guns break when shooting.

### ISSUE THREAD

**Issue by KacperObara** [TommySoucy/H3MP#230]
- Both Host and Client downloaded H3MP + Fallout4 LaserRifle
- Both entered Gun Range scene.
- Client spawns laser rifle, loads it. Does 3 shots, host receives 3 errors. 
- For host, client body freezes.
- Host grabs the same gun, but shooting doesn't work.

Checked with Raygun and Thundergun mods with the same result.
But HLA Combine PulseSMG works correctly.

[HostLogOutput.log](https://github.com/user-attachments/files/16041807/HostLogOutput.log)
[ClientLogOutput.log](https://github.com/user-attachments/files/16041808/ClientLogOutput.log)

**Comment by TommySoucy** [comment]
Thanks ill check it out

**Comment by TommySoucy** [comment]
Problem was that the mod creator didn't setup their custom ammo properly. The fallout 4 laser rifle for example has rounds that are 762_25_tokarev of class Slug, which obviously doesn't exist in vanilla. The laser rifle has a special magazine that already contains these rounds on spawn. But the game has a system to get the prefab of a round for a given class, which H3MP is dependent on for remote clients to know which round the weapon's controller is using. The mod creator did not add the custom round to that system, so remote clients are unable to spawn the same round, throwing an exception instead. This is now handled, in the way that the error is suppressed, and H3MP will fallback to using a default round class for the chamber type. Unfortunately, for that laser rifle for example, the round never gets fired, maybe because the firearm was never supposed to fire the default tokarev FMJ, meaning there won't be a laser or anything on remote clients. At least they don't get an error. If you want this properly fixed, tell the mod creator to fix their mod, to add a round of that type/class to AM.TypeDic
