### ISSUE TITLE
[Feature request] Sosig body model for H3MP

### ISSUE THREAD

**Issue by Aarnoman** [TommySoucy/H3MP#231]
Currently for connected H3MP clients, the player model consists of a coloured geod with visible balls for hand position.
I think it would be a great feature to have the option of a basic sosig player character model if this is feasible. I am unsure of the technical requirements or whether this is possible in the first place, but would be a nice addition if it is. 

Thanks again for an excellent mod, we have been having a ton of fun playing H3VR in multiplayer.

**Comment by TommySoucy** [comment]
I don't take requests.

You can join the H3VR Homebrew discord server: https://discord.gg/83yTrfr
There you can make a bounty and pay for someone to make a mod. Otherwise requesting mods there is against the rules.
People have already been talking about a sosig player body, wouldn't be too hard to find others to pool funds.

Or you can do it yourself. Download the H3MP Unity project:
https://drive.google.com/drive/folders/1HaWLMD7-ZOYZYd3E8f9NrtFQAtqmawwp?usp=drive_link

In there you can check out the default player body prefab to see how it's setup, make your own, then use the H3MPPlayerBodyBuildItem to make a plugin that loads yours into H3MP.

You might want to get the most up to date build item, which is in the unity package you can find at: https://github.com/TommySoucy/H3MP/tree/main/Meatkit

You can download that and import it into the H3MP project, it will ensure you have the latest build item. I don't remember what I changed in there so it's probably best to do it.
