### ISSUE TITLE
Client in TNH game only getting ammo spawn panels @ supply points

### ISSUE THREAD

**Issue by aveganbutcher** [TommySoucy/H3MP#68]
At supply points in TNH, for a client, only the ammo panel is showing up @ supply points, no mag panels and no recycle panels, only the main shop panel and the ammo panel. My friend who was hosting didn't seem to have this problem. I have what I think is the output log here and a picture of the mods I'm using. I saw the same issue in modded maps as well as the vanilla map.
[H3VR output log.txt](https://github.com/TommySoucy/H3MP/files/11085107/H3VR.output.log.txt)
![image](https://user-images.githubusercontent.com/129139897/228124265-55c0e9bd-212e-45c2-9441-3f0b6be77a83.png)

**Comment by TommySoucy** [comment]
I'll check this out soon. thanks

**Comment by TommySoucy** [comment]
Unfortunately logs are just error spam, so couldn't see much, but were seemingly from 2 causes:

Error with tubefed shotgun update upon firing (Fixed)
TNH was desynced (Could not replicate)

This TNH error could explain the secondary panel not appearing in supply points but can't confirmed since I wasn't able to replicate. In all my tests, secondary panel was always there.
I have fixed some things with TNH initialization since last release so if the missing secondary panel is still a thing, reopen the issue and post new logs.
